/* =========================================================
   DUA VERİLERİ
   -----------------------------------------------------------
   Her bölüm için "verses" dizisini kendi Türkçe okunuşu
   metniyle doldur. Her eleman bir ayet/satır olarak ekrana
   basılır. "counterTarget" belirtilen bölümlerde sayaç sayfası
   açıldığında hedef otomatik gösterilir (örn. Esmâ-i Hüsnâ -> 99).
   ========================================================= */

const DUAS = [
  {
    id: "vakia",
    name: "Vâkıa Sûresi",
    meta: "96 âyet",
    note: "Kıyametin kopuş dehşeti, öldükten sonra dirilme, insanların amellerine göre ayrılacağı üç grup (Ashab-ı Meymene, Ashab-ı Meş'eme ve Sabikun) ile cennet ve cehennem ehlinin durumları anlatılır. Ayrıca İslam geleneğinde bolluk ve bereket suresi olarak da bilinir.",
    counterTarget: null,
    cycle: { length: 40 },
    verses: [
      "İzâ veka'atil vâkı'ah.",
      "Leyse livak'atihâ kâzibeh.",
      "Hâfıdatun râfi'ah.",
      "İzâ ruccetil ardu reccâ.",
      "Ve bussetil cibâlu bessâ.",
      "Fe kânet hebâen munbessâ.",
      "Ve kuntum ezvâcen selâseh.",
      "Fe ashâbul meymeneti mâ ashâbul meymeneh.",
      "Ve ashâbul meş'emeti mâ ashâbul meş'emeh.",
      "Ves sâbikûnes sâbikûn.",
      "Ulâikel mukarrabûn.",
      "Fî cennâtin na'îm.",
      "Sulletun minel evvelîn.",
      "Ve kalîlun minel âhırîn.",
      "Alâ sururin mevdûneh.",
      "Muttekîne aleyhâ mutekâbilîn.",
      "Yetûfu aleyhim vildânun muhalledûn.",
      "Bi ekvâbin ve ebârîka ve ke'sin min ma'în.",
      "Lâ yusadda'ûne anhâ ve lâ yunzifûn.",
      "Ve fâkihetin mimmâ yetehayyerûn.",
      "Ve lahmi tayrin mimmâ yeştehûn.",
      "Ve hûrun 'în.",
      "Ke emsâlil lu'luil meknûn.",
      "Cezâen bimâ kânû ya'melûn.",
      "Lâ yesme'ûne fîhâ lagven ve lâ te'sîmâ.",
      "İllâ kîlen selâmen selâmâ.",
      "Ve ashâbul yemîni mâ ashâbul yemîn.",
      "Fî sidrin mahdûd.",
      "Ve talhın mendûd.",
      "Ve zıllin memdûd.",
      "Ve mâin meskûb.",
      "Ve fâkihetin kesîreh.",
      "Lâ maktû'atin ve lâ memnû'ah.",
      "Ve furuşin merfû'ah.",
      "İnnâ enşe'nâhunne inşââ.",
      "Fe ce'alnâhunne ebkârâ.",
      "'Uruben etrâbâ.",
      "Li ashâbil yemîn.",
      "Sulletun minel evvelîn.",
      "Ve sulletun minel âhırîn.",
      "Ve ashâbuş şimâli mâ ashâbuş şimâl.",
      "Fî semûmin ve hamîm.",
      "Ve zıllin min yahmûm.",
      "Lâ bâridin ve lâ kerîm.",
      "İnnehum kânû kable zâlike mutrefîn.",
      "Ve kânû yusırrûne 'alel hınsil 'azîm.",
      "Ve kânû yekûlûne eizâ mitnâ ve kunnâ turâben ve 'ızâmen einnâ le meb'ûsûn.",
      "Eve âbâunel evvelûn.",
      "Kul innel evvelîne vel âhırîn.",
      "Le mecmû'ûne ilâ mîkâti yevmin ma'lûm.",
      "Summe innekum eyyuhed dâllûnel mukezzibûn.",
      "Le âkilûne min şecerin min zakkûm.",
      "Fe mâliûne minhel butûn.",
      "Fe şâribûne aleyhi minel hamîm.",
      "Fe şâribûne şurbel hîm.",
      "Hâzâ nuzuluhum yevmed dîn.",
      "Nahnu halaknâkum fe lev lâ tusaddikûn.",
      "E fe reeytum mâ tumnûn.",
      "E entum tahlukûnehû em nahnul hâlikûn.",
      "Nahnu kaddernâ beynekumul mevte ve mâ nahnu bi mesbûkîn.",
      "Alâ en nubeddile emsâlekum ve nunşiekum fî mâ lâ ta'lemûn.",
      "Ve lekad alimtumun neş'etel ûlâ fe lev lâ tezekkerûn.",
      "E fe reeytum mâ tahrusûn.",
      "E entum tezra'ûnehû em nahnuz zâri'ûn.",
      "Lev neşâu le ce'alnâhu hutâmen fe zaltum tefekkehûn.",
      "İnnâ le mugramûn.",
      "Bel nahnu mahrûmûn.",
      "E fe reeytumul mâellezî teşrebûn.",
      "E entum enzeltumûhu minel muzni em nahnul munzilûn.",
      "Lev neşâu ce'alnâhu ucâcen fe lev lâ teşkurûn.",
      "E fe reeytumun nârelletî tûrûn.",
      "E entum enşe'tum şeceretehâ em nahnul munşiûn.",
      "Nahnu ce'alnâhâ tezkireten ve metâ'an lil mukvîn.",
      "Fe sebbih bismi rabbikel 'azîm.",
      "Fe lâ uksimu bi mevâki'in nucûm.",
      "Ve innehû le kasemun lev ta'lemûne 'azîm.",
      "İnnehû le kur'ânun kerîm.",
      "Fî kitâbin meknûn.",
      "Lâ yemessuhû illel mutahharûn.",
      "Tenzîlun min rabbil 'âlemîn.",
      "E fe bi hâzel hadîsi entum mudhinûn.",
      "Ve tec'alûne rızkakum ennekum tukezzibûn.",
      "Fe lev lâ izâ belegatil hulkûm.",
      "Ve entum hîneizin tenzurûn.",
      "Ve nahnu akrebu ileyhi minkum ve lâkin lâ tubsırûn.",
      "Fe lev lâ in kuntum gayre medînîn.",
      "Terci'ûnehâ in kuntum sâdikîn.",
      "Fe emmâ in kâne minel mukarrabîn.",
      "Fe revhun ve reyhânun ve cennetu na'îm.",
      "Ve emmâ in kâne min ashâbil yemîn.",
      "Fe selâmun leke min ashâbil yemîn.",
      "Ve emmâ in kâne minel mukezzibîned dâllîn.",
      "Fe nuzulun min hamîm.",
      "Ve tasliyetu cahîm.",
      "İnne hâzâ le huvel hakkul yakîn.",
      "Fe sebbih bismi rabbikel 'azîm."
    ]
  },
  {
    id: "tekasur",
    name: "Tekâsür Sûresi",
    meta: "8 âyet",
    note: "Sure, adını ilk ayette geçen ve \"mal, mülk ve çoluk çocuk çokluğuyla övünmek, çoğaltma yarışı yapmak\" anlamına gelen \"tekasür\" kelimesinden alır.",
    counterTarget: null,
    verses: [
      "Bismillâhirrahmânirrahîm",
      "Elhâkumut tekâsur.",
      "Hattâ zurtumul mekâbir.",
      "Kellâ sevfe ta'lemûn.",
      "Summe kellâ sevfe ta'lemûn.",
      "Kellâ lev ta'lemûne 'ılmel yakîn.",
      "Le teravunnel cahîm.",
      "Summe le teravunnehâ 'aynel yakîn.",
      "Summe le tus'elunne yevmeizin 'anin na'îm."
    ]
  },
  {
    id: "humeze",
    name: "Hümeze Sûresi",
    meta: "9 âyet",
    note: "Genel olarak insanları küçük düşürenlerin, malına güvenerek kibirlenenlerin acı sonunu ve cehennem azabını (Hutame) anlatır.",
    counterTarget: null,
    verses: [
      "Bismillâhirrahmânirrahîm",
      "Veylün li-külli hümezetin lümezeh.",
      "Ellezî ceme'a mâlen ve 'addedeh.",
      "Yahsebü enne mâlehû ahledeh.",
      "Kellâ le-yünbezenne fîl-hutameh.",
      "Ve mâ edrâke mel-hutameh.",
      "Nârullâhil-mûkadeh.",
      "Elletî tettali'u 'alel-ef'ideh.",
      "İnnehâ 'aleyhim mü'sadeh.",
      "Fî 'amedin mümeddedeh."
    ]
  },
  {
    id: "duha",
    name: "Duhâ Sûresi",
    meta: "11 âyet",
    note: "Hz. Muhammed'e (s.a.v.) bir süre vahiy gelmemesi üzerine müşriklerin \"Rabbi onu terk etti\" şeklindeki dedikodularına cevap olarak indirilmiştir. Peygamber Efendimiz'i teselli eden, Yüce Allah'ın onu asla terk etmediğini bildiren ve yetimlere, yoksullara iyi davranılmasını öğütleyen çok rahatlatıcı bir suredir.",
    counterTarget: null,
    verses: [
      "Bismillâhirrahmânirrahîm",
      "Ved-duhâ.",
      "Vel-leyli izâ secâ.",
      "Mâ vedde'ake rabbüke ve mâ kalâ.",
      "Ve lel-âhiretü hayrün leke minel-ûlâ.",
      "Ve le-sevfe yu'tîke rabbüke fe-terdâ.",
      "E-lem yecidke yetîmen fe-âvâ.",
      "Ve vecedeke dâllen fe-hedâ.",
      "Ve vecedeke 'âilen fe-agnâ.",
      "Fe-emmel-yetîme felâ takher.",
      "Ve emmes-sâile felâ tenher.",
      "Ve emmâ bi-ni'meti rabbike fe-haddis."
    ]
  },
  {
    id: "amenerrasulu",
    name: "Âmenerrasûlü",
    meta: "Bakara Sûresi, son iki âyet",
    note: "Peygamber Efendimiz (s.a.v.) bu iki ayet için, \"Geceleyin Bakara Suresi'nin son iki ayetini okuyana, bu iki ayet yeter\" buyurmuştur. Genellikle yatsı namazlarından sonra aşr-ı şerif olarak okunur.",
    counterTarget: null,
    verses: [
      "Bismillâhirrahmânirrahîm",
      "Âmener-rasûlü bimâ ünzile ileyhi min rabbihî vel-mü'minûn. Küllün âmene billâhi ve melâiketihî ve kütübihî ve rusulih. Lâ nüferriku beyne ehadin min rusulih. Ve kâlû semi'nâ ve ata'nâ gufrâneke rabbenâ ve ileykel-masîr.",
      "Lâ yükellifullâhü nefsen illâ vüs'ahâ. Lehâ mâ kesebet ve 'aleyhâ mektesebet. Rabbenâ lâ tüâhiznâ in nesînâ ev ahta'nâ. Rabbenâ ve lâ tahmil 'aleynâ ısran kemâ hameltehû 'alellezîne min kablinâ. Rabbenâ ve lâ tühammilnâ mâ lâ tâkate lenâ bih. Va'fü 'annâ, vagfir lenâ, verhamnâ. Ente mevlânâ fensurnâ 'alel-kavmil-kâfirîn."
    ]
  },
  {
    id: "bakara-elif-lam-mim",
    name: "Bakara Sûresi (Elif-Lâm-Mîm)",
    meta: "Bakara Sûresi başlangıcı",
    note: "Kur'an-ı Kerim'deki bazı surelerin başında bulunan ve tek tek okunan bu harflere Hurûf-ı Mukatta'a (kesikli harfler) denir.",
    counterTarget: null,
    verses: [
      "Elif-lâm-mîm.",
      "Zâlikel-kitâbü lâ raybe fîh, hüden lil-müttekîn.",
      "Ellezîne yü'minûne bil-gaybi ve yukîmûnes-salâte ve mimmâ razaknâhüm yünfikûn.",
      "Vellezîne yü'minûne bimâ ünzile ileyke ve mâ ünzile min kablik, ve bil-âhireti hüm yûkınûn.",
      "Ülâike 'alâ hüden min rabbihim ve ülâike hümül-müflihûn."
    ]
  },
  {
    id: "yasin",
    name: "Yâsîn Sûresi (Yâsîn-i Şerîf)",
    meta: "83 âyet · Her Perşembe akşamı",
    note: "Peygamber Efendimiz (s.a.v.) bu sure için, \"Yasin, Kur'an'ın kalbidir\" buyurmuştur. İslam dünyasında cuma gecelerinde, vefat edenlerin arkasından, darlık ve sıkıntı anlarında en çok okunan, fazileti çok yüksek bir suredir. Surede temel olarak tevhid, nübüvvet (peygamberlik), öldükten sonra dirilme ve ahiret hayatı gibi imanın esasları anlatılır.",
    counterTarget: null,
    verses: [
      "Yâsîn",
      "Vel Kur'ân-il hakîm",
      "İnneke leminel mürselîn",
      "Alâ sırâtın müstakîm",
      "Tenzîlel azîzirrahîm",
      "Li tünzira kavmen mâ ünzira âbâühüm fehüm gâfilûn",
      "Lekad hakkal kavlü alâ ekserihim fehüm lâ yü'minûn",
      "İnnâ cealnâ fî a'nâkihim aglâlen fehiye ilel ezkâni fehüm mukmehûn",
      "Ve cealnâ min beyni eydîhim sedden ve min halfihim sedden feağşeynâhüm fehüm lâ yübsirûn",
      "Ve sevâün aleyhim eenzertehüm em lem tünzirhüm lâ yü'minûn",
      "Innemâ tünziru menittebeaz zikra ve haşiyer rahmâne bil ğayb fe beşşirhü bimağfiretiv ve ecrin kerîm",
      "İnnâ nahnü nuhyil mevtâ ve nektübü mâ kaddemû ve âsârehüm ve külle şey'in ahsaynâhü fî imâmin mübîn",
      "Vadrib lehüm meselen ashâbel karyeh. İz câehel mürselûn",
      "İz erselnâ ileyhi müsneyni fekezzebûhümâ fe azzeznâ bisâlisin fekâlû innâ ileyküm mürselûn",
      "Kâlû mâ entüm illâ beşerün mislünâ vemâ enzelerrahmânü min şey'in in entüm illâ tekzibûn",
      "Kâlû rabbünâ ya'lemü innâ ileyküm lemürselûn",
      "Vemâ aleynâ illel belâgul mübîn",
      "Kâlû innâ tetayyernâ biküm lein lem tentehû le nercümenneküm vele yemessenneküm minnâ azâbün elîm",
      "Kâlû tâirüküm meaküm ein zükkirtüm bel entüm kavmün müsrifûn",
      "Vecâe min aksalmedineti racülün yes'â kâle yâ kavmittebiul mürselîn",
      "İttebiû men lâ yeselüküm ecran ve hüm muhtedûn",
      "Vemâ liye lâ a'büdüllezî fetarenî ve ileyhi türceûn",
      "Eettehizü min dûnihî âliheten in yüridnirrahmânü bi-durrin lâ tuğni annî şefâatühüm şey'en velâ yünkizûn",
      "İnnî izen lefî dalâlin mübîn",
      "İnnî âmentü birabbiküm fesmeûn",
      "Kîledhulil cennete, kâle yâleyte kavmî yâ'lemûn",
      "Bimâ gaferelî rabbî ve cealenî minel mükremîn",
      "Vemâ enzelnâ alâ kavmihî min badihî min cündin minessemâi vemâ künnâ münzilîn",
      "İn kânet illâ sayhaten vâhideten feizâhüm hâmidûn",
      "Yâ hasreten alel ibâdi mâ ye'tîhim min resûlin illâ kânûbihî yestehziûn",
      "Elem yerev kem ehleknâ kablehüm minel kurûni ennehüm ileyhim lâ yerciûn",
      "Ve in küllün lemmâ cemî'un ledeynâ muhdarûn",
      "Ve âyetün lehümül ardul meytetü ahyeynâhâ ve ahrecnâ minhâ habben fe minhü ye'külûn",
      "Ve cealnâ fîhâ cennâtin min nahîliv ve a'nâbiv ve feccernâ fîha minel uyûn",
      "Liye'külû min semerihî vemâ amilethü eydîhim efelâ yeşkürûn",
      "Sübhânnellezî halekal ezvâce küllehâ mimmâ tünbitül ardu ve min enfüsihim ve mimmâ lâ ya'lemûn",
      "Ve âyetün lehümülleyü neslehu minhünnehâre fe izâhüm muzlimûn",
      "Veşşemsü tecrî limüstekarrin lehâ zâlike takdîrul azîzil alîm",
      "Velkamere kaddernâhü menâzile hattâ âdekel urcûnil kadîm",
      "Leşşemsû yenbegî lehâ en tüdrikel kamere velelleylü sâbikunnehâr ve küllün fî felekin yesbehûn",
      "Ve âyetül lehüm ennâ hamelnâ zürriyyetehüm fil fülkil meşhûn",
      "Ve halâknâ lehüm min mislihî mâ yarkebûn",
      "Ve in neşe' nugrıkhüm felâ sarîha lehüm velâhüm yünkazûn",
      "İllâ rahmeten minnâ ve metâan ilâ hîn",
      "Ve izâ kîle lehümüttekû mâ beyne eydîküm vemâ halfeküm lealleküm türhamûn",
      "Vemâ te'tîhim min âyetin min âyâti rabbihim illâ kânû anhâ mu'ridîn",
      "Ve izâ kîle lehüm enfikû mim mâ rezakakümüllâhü, kâlellezîne keferû, lillezîne âmenû enut'ımü menlev yeşâullâhü et'ameh, in entüm illâ fî dalâlin mübîn",
      "Ve yekûlûne metâ hâzel va'dü in küntüm sâdikîn",
      "Mâ yenzurûne illâ sayhaten vâhideten te'huzühüm vehüm yehissimûn",
      "Felâ yestetîûne tavsıyeten velâ ilâ ehlihim yerciûn",
      "Ve nüfiha fîssûri feizâhüm minel ecdâsi ilâ rabbihim yensilûn",
      "Kâlû yâ veylenâ men beasena min merkadina hâzâ mâ veaderrahmânü ve sadekal mürselûn",
      "İn kânet illâ sayhaten vâhideten feizâ hüm cemî'un ledeynâ muhdarûn",
      "Felyevme lâ tuzlemu nefsün şeyen velâ tüczevne illâ mâ küntüm tâ'melûn",
      "İnne ashâbel cennetil yevme fîşüğulin fâkihûn",
      "Hüm ve ezvâcühüm fî zılâlin alel erâiki müttekiûn",
      "Lehüm fîhâ fâkihetün ve lehüm mâ yeddeûn",
      "Selâmün kavlen min rabbin rahîm",
      "Vemtâzül yevme eyyühel mücrimûn",
      "Elem a'hed ileyküm yâ benî âdeme en lâ tâ'buduşşeytân innehû leküm adüvvün mübîn",
      "Ve enî'budûnî, hâzâ sırâtun müstekîm",
      "Ve lekad edalle minküm cibillen kesîran efelem tekûnû ta'kılûn",
      "Hâzihî cehennemülletî küntüm tûadûn",
      "Lslevhel yevme bimâ küntüm tekfürûn",
      "Elyevme nahtimü alâ efvâhihim ve tükellimünâ eydîhim ve teşhedü ercülühüm bimâ kânû yeksibûn",
      "Velev neşâü letamesnâ alâ a'yunihim festebekus sırâta fe ennâ yübsirûn",
      "Velev neşâü lemesahnâhüm alâ mekânetihim femestetâû mudıyyev velâ yerciûn",
      "Ve men nüammirhü nünekkishü filhalkı, efelâ ya'kilûn",
      "Ve mâ allemnâhüşşi'ra vemâ yenbegî leh in hüve illâ zikrün ve kur'ânün mübîn",
      "Liyünzira men kâne hayyen ve yehıkkal kavlü alel kâfirîn",
      "Evelem yerav ennâ halaknâ lehüm mimmâ amilet eydîna en âmen fehüm lehâ mâlikûn",
      "Ve zellelnâhâ lehüm feminhâ rekûbühüm ve minhâ ye'külûn",
      "Ve lehüm fîhâ menâfiu ve meşâribü efelâ yeşkürûn",
      "Vettehazû min dûnillâhi âliheten leallehüm yünsarûn",
      "Lâ yestetîûne nasrahüm ve hüm lehüm cündün muhdarûn",
      "Felâ yahzünke kavlühüm. İnnâ na'lemü mâ yüsirrûne vemâ yu'linûn",
      "Evelem yeral insânü ennâ halaknâhü min nutfetin feizâ hüve hasîmün mübîn",
      "Ve darebe lenâ meselen ve nesiye halkah kale men yuhyil izâme ve hiye ramîm",
      "Kul yuhyihellezî enşeehâ evvele merrah ve hüve bikülli halkın alîm",
      "Ellezî ceale leküm mineşşeceril ahdari nâren feizâ entüm minhü tûkidûn",
      "Eveleysellezî halakassemâvati vel arda bikâdirin alâ ey yahlüka mislehüm, belâ ve hüvel hallâkul alîm",
      "İnnema emrühû izâ erâde şey'en en yekûle lehû kün, feyekûn",
      "Fesübhanellezî biyedihî melekûtü külli şey'in ve ileyhi türceûn."
    ]
  },
  {
    id: "alak",
    name: "Alak Sûresi",
    meta: "19 âyet",
    note: "Okumanın, ilmin, kalemin ve öğrenmenin önemini vurgular. İnsana aslı hatırlatılarak kibirlenmemesi istenir.",
    counterTarget: null,
    verses: [
      "Bismillâhirrahmânirrahîm",
      "Ikra' bismi rabbikellezî halak. Halakal insâne min alak.",
      "Ikra' ve rabbukel ekrem. Ellezî alleme bil kalem. Allemel insâne mâ lem ya'lem.",
      "Kellâ innel insâne le yatgâ. En raâhustagnâ. İnne ilâ rabbiker ruc'â.",
      "E raeytellezî yenhâ. Abden izâ sallâ.",
      "E raeyte in kâne alâl hudâ. Ev emera bit takvâ. E raeyte in kezzebe ve tevellâ.",
      "E lem ya'lem bi ennellâhe yerâ.",
      "Kellâ le in lem yentehi le nesfean bin nâsıyeti. Nâsiyetin kâzibetin hâtıetin. Felyed'u nâdiyehu. Se ned'uz zebâniyete. Kellâ, lâ tutı'hu vescud vakterib."
    ]
  },
  {
    id: "esmaulhusna",
    name: "Esmâ-i Hüsnâ",
    meta: "Allah'ın 99 ismi",
    note: "Sayaç 99 hedefiyle açılır, isimleri tek tek sayarak okuyabilirsin.",
    counterTarget: 99,
    verses: [
      "[[Esmâ-i Hüsnâ listesi (99 isim, Türkçe okunuşuyla) buraya eklenecek.]]"
    ]
  }
];

/* =========================================================
   TESBİHAT VERİLERİ
   ========================================================= */

const TESBIHAT = [
  {
    id: "rizik-bereket",
    name: "Rızık ve Bereket",
    meta: "20 kez",
    note: null,
    verses: [
      "Yâ İlâhel Âliheter-Refîi Celâlühü"
    ]
  },
  {
    id: "borctan-kurtulma",
    name: "Borçtan Kurtulma",
    meta: "20 kez",
    note: null,
    verses: [
      "Allahümme'kfinî bi halâlike an harâmike ve ağninî bi fadlike ammen sivâke."
    ]
  }
];
